package power

import (
	"strconv"
	"strings"
)

// The monitor attaches itself. Every alternative needed the team to edit their
// OpModes, and a diagnostic somebody has to wire into twelve OpModes is one
// they will wire into none of them.
//
// @OnCreateEventLoop marks a static method the robot controller calls with the
// event loop it has just built, which is where the OpMode manager comes from.
// FtcDashboard uses the same hook for the same reason, and it is worth being
// precise about why: the robot controller offers several hooks, and the one
// that hands over a web server cannot hand over an OpMode manager. Reaching for
// the manager through the activity at web-server time finds nothing, silently,
// on a robot where the activity is not up yet.
//
// It also fires again every time the robot is restarted, which the startup
// hooks do not, so the monitor survives a restart instead of quietly detaching.
//
// Sampling happens on its own thread rather than in the OpMode loop. It still
// costs time, because the Lynx bus serialises, but the cost lands on a thread
// that is not holding up the robot rather than between two lines of somebody's
// drive code.

// Package is where the generated monitor lives inside the team's project.
const Package = "pusherpower"

// Class is the generated file, without its extension.
const Class = "PusherPowerMonitor"

// Marker identifies the file as generated, so removing it never removes
// something a person wrote.
const Marker = "// generated by pusher: power monitor"

// sourceFor is the monitor with a sampling period baked into it.
//
// Baked in rather than read at runtime: the monitor runs on a robot with no
// access to this laptop's settings, and a diagnostic that needs a config file
// pushed alongside it is one more thing to get out of step.
func sourceFor(periodMS int) string {
	if periodMS <= 0 {
		periodMS = 100
	}
	return strings.Replace(source, "%PERIOD%", strconv.Itoa(periodMS), 1)
}

// source is the monitor, as it is written into the project.
//
// Deliberately one self-contained file with no dependency on anything pusher
// ships: it is compiled by the team's own Gradle build, on a machine pusher does
// not control, against whichever SDK version they are on.
const source = Marker + `
//
// Reads how much current each motor and each hub is drawing while an OpMode
// runs, and writes what it saw when the OpMode stops. Turn it off in
// ` + "`pusher settings`" + `, which deletes this file.
//
// THIS COSTS LOOP TIME. A motor's current cannot be read in a bulk transfer:
// the bulk packet carries an over-current flag but not the value, so every
// reading here is its own round trip over the RS485 bus. Do not run this in a
// match.
package org.firstinspires.ftc.teamcode.` + Package + `;

import android.content.Context;

import com.qualcomm.ftccommon.FtcEventLoop;
import com.qualcomm.hardware.lynx.LynxModule;
import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.OpModeManagerImpl;
import com.qualcomm.robotcore.eventloop.opmode.OpModeManagerNotifier;
import com.qualcomm.robotcore.hardware.DcMotorEx;
import com.qualcomm.robotcore.hardware.HardwareDevice;
import com.qualcomm.robotcore.hardware.HardwareMap;
import com.qualcomm.robotcore.util.RobotLog;

import org.firstinspires.ftc.ftccommon.external.OnCreateEventLoop;
import org.firstinspires.ftc.robotcore.external.navigation.CurrentUnit;
import org.firstinspires.ftc.robotcore.external.navigation.VoltageUnit;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;

public final class ` + Class + ` implements OpModeManagerNotifier.Notifications {

    public static final String TAG = "PusherPower";

    /** Where the recordings are written, which is where pusher reads them from. */
    public static final String DIR = "/sdcard/FIRST/pusher-power";

    /**
     * How often every device is read.
     *
     * Each tick is one bus round trip per device, so this is the whole cost of
     * the feature. Ten a second is enough to catch a stall and slow enough to
     * leave the bus mostly to the robot.
     */
    public static final long PERIOD_MS = %PERIOD%;

    /**
     * How many ticks are kept for the graphs.
     *
     * Ten minutes at the sampling rate, which is longer than any practice run.
     * Past that the totals go on being correct and the graph stops growing,
     * because a robot left switched on should not fill its own storage.
     */
    public static final int MAX_SAMPLES = 6000;

    private static ` + Class + ` instance;
    private static OpModeManagerImpl attachedTo;

    private final List<Tracked> tracked = new ArrayList<>();

    // Kept as floats: the graph is drawn a few hundred pixels wide, and doubles
    // would double what a long run holds in memory for precision nobody can see.
    private final List<Limelight> limelights = new ArrayList<>();

    private float[] times;
    private float[] volts;
    private int ticks;
    private Thread sampler;
    private volatile boolean running;

    private String opModeName = "";
    private boolean recording;
    private long startedAt;
    private double peakVolts;
    private double lowVolts = Double.MAX_VALUE;

    /**
     * Called by the robot controller with the event loop it has just built.
     *
     * Called again on every robot restart, so the old registration is dropped
     * first: the manager is new each time, and a listener left on the old one
     * is a listener that never hears anything again.
     */
    @OnCreateEventLoop
    public static void attach(Context context, FtcEventLoop eventLoop) {
        try {
            OpModeManagerImpl manager = eventLoop.getOpModeManager();
            if (manager == null) {
                problem("The robot controller handed over an event loop with no OpMode manager on it, "
                        + "so the monitor could not attach. Nothing was recorded.");
                return;
            }

            if (instance == null) {
                instance = new ` + Class + `();
            }
            if (attachedTo != null && attachedTo != manager) {
                attachedTo.unregisterListener(instance);
            }

            attachedTo = manager;
            manager.registerListener(instance);

            RobotLog.ii(TAG, "power monitor attached; this costs loop time, do not use it in a match");
        } catch (Exception e) {
            // A diagnostic that stops the robot app from starting is worse than
            // no diagnostic at all.
            RobotLog.ee(TAG, e, "could not attach the power monitor");
            problem("The monitor could not attach: " + e);
        }
    }

    /**
     * Leaves a note saying why nothing was recorded.
     *
     * The log would do, if anybody could read it. It is a ring buffer on a robot
     * somebody has to plug into, and by the time they wonder why there are no
     * recordings the line has usually gone. A file sits in the same place the
     * recordings do, so whatever asks for them finds the explanation instead of
     * an empty directory.
     */
    private static void problem(String message) {
        RobotLog.ee(TAG, message);

        FileWriter w = null;
        try {
            File dir = new File(DIR);
            if (!dir.exists() && !dir.mkdirs()) {
                return;
            }

            w = new FileWriter(new File(dir, "problem-" + System.currentTimeMillis() + ".txt"));
            w.write("pusher-power-problem 1\n");
            w.write(message + "\n");
        } catch (Exception e) {
            // Nothing left to try. Failing to write down why something failed
            // is not worth a second failure on top of it.
        } finally {
            if (w != null) {
                try {
                    w.close();
                } catch (IOException ignored) {
                }
            }
        }
    }

    @Override
    public void onOpModePreInit(OpMode opMode) {
    }

    @Override
    public void onOpModePreStart(OpMode opMode) {
        stopSampling();

        // The robot controller runs an OpMode of its own between the real ones,
        // and it gets these callbacks too. Sampling it would leave the bus busy
        // forever after the first run, because the robot is never not running
        // that one, and stopping it would write a recording of nobody driving.
        if (isDefault(opMode)) {
            return;
        }

        tracked.clear();
        peakVolts = 0;
        lowVolts = Double.MAX_VALUE;
        opModeName = opMode.getClass().getSimpleName();

        HardwareMap map = opMode.hardwareMap;
        if (map == null) {
            return;
        }

        for (DcMotorEx motor : map.getAll(DcMotorEx.class)) {
            tracked.add(new Tracked(nameOf(map, motor), "motor", motor, null));
        }
        for (LynxModule hub : map.getAll(LynxModule.class)) {
            String name = nameOf(map, hub);

            tracked.add(new Tracked(name, "hub", null, hub));

            // The other two rails the hub can measure. Servos have no current
            // sensing of their own, and neither do I2C sensors, so these are
            // the only readings there are for either: one number for all the
            // servos, one for everything on I2C.
            tracked.add(new Tracked(name + ":servos", "bus", null, hub));
            tracked.add(new Tracked(name + ":i2c", "bus", null, hub));
        }

        findLimelights(map);

        if (tracked.isEmpty()) {
            problem("No motors or hubs in the hardware map for " + opModeName
                    + ", so there was nothing to measure.");
            return;
        }

        times = new float[MAX_SAMPLES];
        volts = new float[MAX_SAMPLES];
        ticks = 0;

        for (int i = 0; i < tracked.size(); i++) {
            tracked.get(i).series = new float[MAX_SAMPLES];
        }

        startedAt = System.nanoTime();
        recording = true;
        running = true;
        sampler = new Thread(new Runnable() {
            @Override
            public void run() {
                sample();
            }
        }, "pusher-power");
        sampler.setDaemon(true);
        sampler.start();
    }

    @Override
    public void onOpModePostStop(OpMode opMode) {
        stopSampling();

        if (isDefault(opMode) || !recording) {
            return;
        }

        // Cleared before writing rather than after, so a second stop cannot
        // write the same run out twice however it arrives.
        recording = false;
        write();
    }

    /**
     * The OpMode the robot controller runs when no real one is selected.
     *
     * Recognised by type rather than by name, because the name it is given is
     * not part of anything anybody promised to keep.
     */
    private static boolean isDefault(OpMode opMode) {
        return opMode instanceof OpModeManagerImpl.DefaultOpMode;
    }

    private void sample() {
        while (running) {
            long tick = System.nanoTime();
            double seconds = (tick - startedAt) / 1e9;
            double atVolts = 0;

            int slot = ticks < MAX_SAMPLES ? ticks : -1;

            for (int i = 0; i < tracked.size() && running; i++) {
                Tracked t = tracked.get(i);
                try {
                    double amps;
                    if (t.motor != null) {
                        amps = t.motor.getCurrent(CurrentUnit.AMPS);
                    } else if (t.name.endsWith(":servos")) {
                        amps = t.hub.getGpioBusCurrent(CurrentUnit.AMPS);
                    } else if (t.name.endsWith(":i2c")) {
                        amps = t.hub.getI2cBusCurrent(CurrentUnit.AMPS);
                    } else {
                        amps = t.hub.getCurrent(CurrentUnit.AMPS);

                        double v = t.hub.getInputVoltage(VoltageUnit.VOLTS);
                        if (v > 0) {
                            atVolts = v;
                            if (v > peakVolts) {
                                peakVolts = v;
                            }
                            if (v < lowVolts) {
                                lowVolts = v;
                            }
                        }
                    }

                    t.add(amps, seconds);
                    if (slot >= 0 && amps >= 0) {
                        t.series[slot] = (float) amps;
                    }
                } catch (Exception e) {
                    // A device that will not answer is not worth ending the
                    // recording over; the rest of them still say something.
                    t.failures++;
                }
            }

            for (int i = 0; i < limelights.size() && running; i++) {
                limelights.get(i).read();
            }

            if (slot >= 0) {
                times[slot] = (float) seconds;
                volts[slot] = (float) atVolts;
            }
            ticks++;

            long spent = (System.nanoTime() - tick) / 1000000L;
            long rest = PERIOD_MS - spent;
            if (rest > 0) {
                try {
                    Thread.sleep(rest);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    return;
                }
            }
        }
    }

    private void stopSampling() {
        running = false;

        Thread t = sampler;
        sampler = null;
        if (t == null) {
            return;
        }

        t.interrupt();
        try {
            t.join(500);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }

    /**
     * Writes what the run drew, once, after it has ended.
     *
     * Nothing is written while the OpMode is running: the recording is a few
     * hundred bytes and holding it in memory costs nothing, whereas touching
     * the filesystem mid-run would add a cost nobody asked for on top of the
     * one they did.
     */
    private void write() {
        if (tracked.isEmpty()) {
            return;
        }

        double elapsed = (System.nanoTime() - startedAt) / 1e9;

        File dir = new File(DIR);
        if (!dir.exists() && !dir.mkdirs()) {
            RobotLog.ee(TAG, "cannot create " + DIR);
            return;
        }

        File out = new File(dir, opModeName + "-" + System.currentTimeMillis() + ".txt");

        FileWriter w = null;
        try {
            w = new FileWriter(out);

            w.write("pusher-power 1\n");
            w.write("opmode " + opModeName + "\n");
            w.write(String.format(Locale.US, "seconds %.3f\n", elapsed));
            w.write(String.format(Locale.US, "period %d\n", PERIOD_MS));

            if (lowVolts != Double.MAX_VALUE) {
                w.write(String.format(Locale.US, "volts %.2f %.2f\n", lowVolts, peakVolts));
            }

            for (Iterator<Tracked> it = tracked.iterator(); it.hasNext(); ) {
                Tracked t = it.next();
                if (t.samples == 0) {
                    continue;
                }
                w.write(String.format(Locale.US, "device %s %s %d %.4f %.4f %.3f %d\n",
                        t.name, t.kind, t.samples, t.total / t.samples, t.peak, t.peakAt, t.failures));
            }

            for (Iterator<Limelight> it = limelights.iterator(); it.hasNext(); ) {
                Limelight l = it.next();
                if (l.samples == 0) {
                    continue;
                }
                w.write(String.format(Locale.US, "limelight %s %.0f %.1f %.1f\n",
                        l.name, 100.0 * l.connected / l.samples,
                        l.fps / l.samples, l.cpu / l.samples));
            }

            // The readings themselves, for drawing. Written after the totals so
            // anything that only understands the totals can stop reading here:
            // a line it does not recognise is one it skips.
            writeSeries(w);
        } catch (IOException e) {
            RobotLog.ee(TAG, e, "cannot write " + out);
        } finally {
            if (w != null) {
                try {
                    w.close();
                } catch (IOException ignored) {
                }
            }
        }
    }

    /**
     * Every reading, one line per tick: the time, the battery, then one current
     * per device in the order the header names them.
     *
     * One line per tick rather than one per reading, because a tick is when
     * they were all taken and a graph wants them lined up.
     */
    private void writeSeries(FileWriter w) throws IOException {
        StringBuilder head = new StringBuilder("series");
        for (Iterator<Tracked> it = tracked.iterator(); it.hasNext(); ) {
            head.append(' ').append(it.next().name);
        }
        w.write(head.append('\n').toString());

        int kept = Math.min(ticks, MAX_SAMPLES);
        if (kept < ticks) {
            w.write(String.format(Locale.US, "truncated %d %d\n", kept, ticks));
        }

        StringBuilder line = new StringBuilder(64);
        for (int i = 0; i < kept; i++) {
            line.setLength(0);
            line.append("s ").append(String.format(Locale.US, "%.2f %.2f", times[i], volts[i]));

            for (int d = 0; d < tracked.size(); d++) {
                line.append(String.format(Locale.US, " %.2f", tracked.get(d).series[i]));
            }

            w.write(line.append('\n').toString());
        }
    }

    /**
     * Finds any Limelight, for the load it reports rather than the current it
     * draws.
     *
     * It cannot report current: it is not on a rail the hub measures, so
     * whatever it takes shows up inside the hub's own total and nowhere else.
     * What it can say is how hard it is working, which is the next best thing
     * and is worth having beside everything else.
     *
     * Found by name through reflection rather than by importing it, because a
     * team on an SDK without that class would otherwise fail to compile a file
     * they did not write.
     */
    private void findLimelights(HardwareMap map) {
        limelights.clear();

        for (HardwareDevice device : map.getAll(HardwareDevice.class)) {
            if (!device.getClass().getName().toLowerCase(Locale.US).contains("limelight")) {
                continue;
            }
            try {
                limelights.add(new Limelight(nameOf(map, device), device));
            } catch (Exception ignored) {
                // Something that looks like a Limelight and does not behave
                // like one is not worth a failed recording.
            }
        }
    }

    private static String nameOf(HardwareMap map, Object device) {
        for (String name : map.getNamesOf((com.qualcomm.robotcore.hardware.HardwareDevice) device)) {
            return name.replace(' ', '_');
        }
        return "unnamed";
    }

    /**
     * A Limelight, read through reflection so this file compiles against an SDK
     * that has never heard of one.
     */
    private static final class Limelight {
        final String name;
        final Object device;
        final java.lang.reflect.Method isConnected;
        final java.lang.reflect.Method getStatus;

        int samples;
        int connected;
        double fps;
        double cpu;

        Limelight(String name, Object device) throws Exception {
            this.name = name;
            this.device = device;
            this.isConnected = device.getClass().getMethod("isConnected");
            this.getStatus = device.getClass().getMethod("getStatus");
        }

        void read() {
            try {
                samples++;
                if (Boolean.TRUE.equals(isConnected.invoke(device))) {
                    connected++;
                }

                Object status = getStatus.invoke(device);
                if (status == null) {
                    return;
                }

                fps += ((Number) status.getClass().getMethod("getFps").invoke(status)).doubleValue();
                cpu += ((Number) status.getClass().getMethod("getCpu").invoke(status)).doubleValue();
            } catch (Exception ignored) {
                // A camera that will not answer is not worth ending the
                // recording over.
            }
        }
    }

    private static final class Tracked {
        final String name;
        final String kind;
        final DcMotorEx motor;
        final LynxModule hub;

        float[] series;

        int samples;
        int failures;
        double total;
        double peak;
        double peakAt;

        Tracked(String name, String kind, DcMotorEx motor, LynxModule hub) {
            this.name = name;
            this.kind = kind;
            this.motor = motor;
            this.hub = hub;
        }

        void add(double amps, double at) {
            if (amps < 0) {
                return;
            }
            samples++;
            total += amps;
            if (amps > peak) {
                peak = amps;
                peakAt = at;
            }
        }
    }
}
`
