package extreme

import (
	"archive/zip"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// The bridge is how a library in the APK gets to see reloaded code.
//
// A reloaded class sits below the APK in the classloader chain, so nothing in
// the APK can reach it. But the SDK invokes @OpModeRegistrar methods through
// the same filter that finds OpModes, and that filter does see reloaded
// classes. So a generated class in the reload dex runs on every reload, with
// the reloaded classes in hand, and can give them to anything that would
// otherwise have to go looking.
//
// That is the general mechanism. A library that needs reloaded code handled
// gets a hook here rather than a warning in a menu.

// bridgePackage is where the generated class lives. Under the team package so
// it is excluded from the APK with everything else, and in a subpackage of its
// own so it cannot collide with a team's own class.
const bridgePackage = "org.firstinspires.ftc.teamcode.pusherextreme"

const bridgeClass = "PusherExtremeBridge"

// dashboardMarker identifies FtcDashboard on the classpath.
const dashboardMarker = "com/acmerobotics/dashboard/FtcDashboard.class"

// bridgeHead is the part that is always generated.
//
// It deliberately does nothing global. An earlier version set the thread
// context classloader here, on the theory that a library resolving classes that
// way would start working for free. That was speculation: none of pedro,
// Panels, EasyOpenCV or blob resolve classes at all. What it actually did was
// repoint an SDK-owned thread at a classloader that is discarded on the next
// reload, leaving that thread resolving through a dead loader.
const bridgeHead = `package ` + bridgePackage + `;

import android.content.Context;
import com.qualcomm.robotcore.eventloop.opmode.AnnotatedOpModeManager;
import com.qualcomm.robotcore.eventloop.opmode.OpModeRegistrar;

/** Generated by pusher. Hands reloaded classes to libraries that cannot see them. */
public final class ` + bridgeClass + ` {

    private ` + bridgeClass + `() {
    }

    @OpModeRegistrar
    public static void register(Context context, AnnotatedOpModeManager manager) {
        registerDashboardConfigs();
    }
`

// bridgeNoDashboard is used when FtcDashboard is not on the classpath, so the
// generated file never references a library the project does not have.
const bridgeNoDashboard = `
    private static void registerDashboardConfigs() {
    }
}
`

// GenerateBridge writes the bridge into the source set being compiled.
//
// Returns the file to add to the compile, or empty when there is nothing for
// the bridge to do.
func GenerateBridge(work string, configs, previous []string, cp Classpath) (string, error) {
	body := bridgeNoDashboard

	if onClasspath(cp, dashboardMarker) && (len(configs) > 0 || len(previous) > 0) {
		body = dashboardBody(configs, stale(configs, previous))
	}

	dir := filepath.Join(work, "generated", filepath.FromSlash(strings.ReplaceAll(bridgePackage, ".", "/")))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}

	path := filepath.Join(dir, bridgeClass+".java")
	if err := os.WriteFile(path, []byte(bridgeHead+body), 0o644); err != nil {
		return "", err
	}

	return path, nil
}

// dashboardBody registers each @Config class with the dashboard by hand.
//
// FtcDashboard finds these by scanning the base APK, which a reloaded class is
// not in. Everything used here is public API: withConfigRoot, putVariable and
// createVariableFromClass.
//
// Each class is registered separately and wrapped, because one that cannot be
// reflected over must not take the rest with it.
// stale is the names registered last time that are not being registered now.
//
// Dashboard's config root outlives the reload, so an entry put there by an
// earlier one stays, holding a Class from a classloader that no longer exists.
// That is both a dead section in the dashboard for a class you deleted and a
// reference into a discarded loader.
func stale(configs, previous []string) []string {
	current := map[string]bool{}
	for _, name := range configs {
		current[simpleName(name)] = true
	}

	var out []string
	for _, name := range previous {
		if !current[name] {
			out = append(out, name)
		}
	}
	return out
}

// simpleName is what dashboard files a config class under.
func simpleName(qualified string) string {
	if i := strings.LastIndex(qualified, "."); i >= 0 {
		return qualified[i+1:]
	}
	return qualified
}

// RegisteredNames is what this reload will put into the dashboard, recorded so
// the next one can take away what it no longer registers.
func RegisteredNames(configs []string) []string {
	out := make([]string, 0, len(configs))
	for _, name := range configs {
		out = append(out, simpleName(name))
	}
	return out
}

func dashboardBody(configs, gone []string) string {
	var b strings.Builder

	b.WriteString(`
    private static void registerDashboardConfigs() {
        try {
            final com.acmerobotics.dashboard.FtcDashboard dashboard =
                    com.acmerobotics.dashboard.FtcDashboard.getInstance();
            if (dashboard == null) {
                return;
            }

            dashboard.withConfigRoot(new com.acmerobotics.dashboard.CustomVariableConsumer() {
                @Override
                public void accept(com.acmerobotics.dashboard.config.variable.CustomVariable root) {
`)

	for _, name := range gone {
		fmt.Fprintf(&b, `                    drop(root, "%s");
`, name)
	}

	for _, name := range configs {
		fmt.Fprintf(&b, `                    put(root, %s.class);
`, name)
	}

	b.WriteString(`                }
            });

            dashboard.updateConfig();
        } catch (Throwable ignored) {
        }
    }

    private static void put(com.acmerobotics.dashboard.config.variable.CustomVariable root,
                            Class<?> clazz) {
        try {
            root.putVariable(clazz.getSimpleName(),
                    com.acmerobotics.dashboard.config.reflection.ReflectionConfig
                            .createVariableFromClass(clazz));
        } catch (Throwable ignored) {
        }
    }

    private static void drop(com.acmerobotics.dashboard.config.variable.CustomVariable root,
                             String name) {
        try {
            root.removeVariable(name);
        } catch (Throwable ignored) {
        }
    }
}
`)

	return b.String()
}

// onClasspath reports whether a class is on the compile classpath, so the
// generated file only mentions libraries the project actually has.
func onClasspath(cp Classpath, entry string) bool {
	for _, jar := range cp.Compile {
		archive, err := zip.OpenReader(jar)
		if err != nil {
			continue
		}

		for _, file := range archive.File {
			if file.Name == entry {
				archive.Close()
				return true
			}
		}
		archive.Close()
	}
	return false
}

// ConfigClasses is the fully qualified name of every reloaded class something
// in the APK reads by scanning.
//
// Anything kept in the APK is left out: it is found the ordinary way, and
// registering it twice would put it in the dashboard twice.
func ConfigClasses(root string, keep []string) []string {
	var out []string

	for _, r := range FindReflected(root).Classes {
		if inAny(r.Package+"/", keep) {
			continue
		}

		name := strings.ReplaceAll(r.Package, "/", ".") + "." + r.Class
		out = append(out, name)
	}

	return out
}
