package profile

import (
	"strconv"
	"strings"
)

// The profiler attaches itself, the same way the power monitor does and for the
// same reason: a diagnostic somebody has to wire into twelve OpModes is one
// they will wire into none of them. @OnCreateEventLoop hands over the event
// loop the robot controller has just built, which is where the OpMode manager
// comes from, and it fires again on every restart.
//
// What it does is sample stacks. A thread wakes up every few milliseconds, asks
// the thread running the OpMode what it is in the middle of, and adds that
// stack to a tree. Time is then counted in samples: a method that shows up in
// half of them was running for half the run. That is what a flame chart is, and
// it is the only way to find out where loop time goes without asking somebody
// to instrument every method they might suspect.
//
// The thread to sample is found by looking for the OpMode's own class in the
// stacks rather than by name. The SDK does not promise a thread name, and it
// runs iterative OpModes on the event loop thread and LinearOpModes on one of
// their own, so a name would have been two guesses rather than one.

// Package is where the generated profiler lives inside the team's project.
const Package = "pusherprofile"

// Class is the generated file, without its extension.
const Class = "PusherLoopProfiler"

// Marker identifies the file as generated, so removing it never removes
// something a person wrote.
const Marker = "// generated by pusher: loop profiler"

// sourceFor is the profiler with a sampling period baked into it.
//
// Baked in rather than read at runtime: it runs on a robot with no access to
// this laptop's settings, and a diagnostic that needs a config file pushed
// beside it is one more thing to fall out of step.
func sourceFor(periodMS int) string {
	if periodMS <= 0 {
		periodMS = DefaultPeriod
	}
	return strings.Replace(source, "%PERIOD%", strconv.Itoa(periodMS), 1)
}

const source = Marker + `
//
// Samples what the robot is in the middle of while an OpMode runs, and writes a
// flame chart of it when the OpMode stops. Turn it off in ` + "`pusher settings`" + `,
// which deletes this file.
//
// THIS COSTS LOOP TIME. Reading another thread's stack makes that thread stop
// for as long as it takes to walk it, so a deep stack sampled often is a real
// cost. It is small at the default rate and it is not nothing. Do not run this
// in a match.
package org.firstinspires.ftc.teamcode.` + Package + `;

import android.content.Context;

import com.qualcomm.ftccommon.FtcEventLoop;
import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.OpModeManagerImpl;
import com.qualcomm.robotcore.eventloop.opmode.OpModeManagerNotifier;
import com.qualcomm.robotcore.util.RobotLog;

import org.firstinspires.ftc.ftccommon.external.OnCreateEventLoop;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

public final class ` + Class + ` implements OpModeManagerNotifier.Notifications {

    public static final String TAG = "PusherProfile";

    /** Where the recordings are written, which is where pusher reads them from. */
    public static final String DIR = "/sdcard/FIRST/pusher-profile";

    /**
     * How often the OpMode's thread is asked what it is doing.
     *
     * This is the whole cost of the feature. Every sample stops that thread for
     * as long as it takes to walk its stack, so halving this doubles the cost.
     */
    public static final long PERIOD_MS = %PERIOD%;

    /** How many samples one run keeps, after which it stops growing. */
    public static final int MAX_SAMPLES = 60000;

    /** How many distinct call paths one run keeps. */
    public static final int MAX_NODES = 8000;

    /** How deep a single stack is followed. */
    public static final int MAX_DEPTH = 128;

    private static ` + Class + ` instance;
    private static OpModeManagerImpl attachedTo;

    /** One call path, and how many samples ended in it. */
    private static final class Node {
        final int id;
        final Node parent;
        final String name;
        int self;
        Map<String, Node> kids;

        Node(int id, Node parent, String name) {
            this.id = id;
            this.parent = parent;
            this.name = name;
        }
    }

    private final List<Node> nodes = new ArrayList<>();
    private Node root;

    // The timeline, run length encoded: which call path was on top, and for how
    // many samples in a row. A run that sits in one method for a second is one
    // pair rather than a hundred, which is what keeps this small enough to write.
    private final List<int[]> runs = new ArrayList<>();

    private volatile boolean running;
    private Thread sampler;
    private Thread target;

    private String opModeName = "";
    private String opModeClass = "";
    private boolean recording;
    private long startedAt;
    private long startedNanos;
    private int samples;
    private int missed;
    private int truncated;

    /**
     * Called by the robot controller with the event loop it has just built.
     *
     * Called again on every robot restart, so the old registration is dropped
     * first: the manager is new each time, and a listener left on the old one
     * never hears anything again.
     */
    @OnCreateEventLoop
    public static void attach(Context context, FtcEventLoop eventLoop) {
        try {
            OpModeManagerImpl manager = eventLoop.getOpModeManager();
            if (manager == null) {
                problem("The robot controller handed over an event loop with no OpMode manager on it, "
                        + "so the profiler could not attach. Nothing was recorded.");
                return;
            }

            if (instance == null) {
                instance = new ` + Class + `();
            }
            if (attachedTo != null && attachedTo != manager) {
                attachedTo.unregisterListener(instance);
            }

            attachedTo = manager;
            manager.registerListener(instance);

            RobotLog.ii(TAG, "loop profiler attached; this costs loop time, do not use it in a match");
        } catch (Exception e) {
            // A diagnostic that stops the robot app from starting is worse than
            // no diagnostic at all.
            RobotLog.ee(TAG, e, "could not attach the loop profiler");
            problem("The profiler could not attach: " + e);
        }
    }

    /**
     * Leaves a note saying why nothing was recorded.
     *
     * The log would do, if anybody could read it. It is a ring buffer on a robot
     * somebody has to plug into, and by the time they wonder why there are no
     * recordings the line has gone. A file sits where the recordings do, so
     * whatever asks for them finds the explanation instead of an empty
     * directory.
     */
    private static void problem(String message) {
        RobotLog.ee(TAG, message);

        FileWriter w = null;
        try {
            File dir = new File(DIR);
            if (!dir.exists() && !dir.mkdirs()) {
                return;
            }
            w = new FileWriter(new File(dir, "problem-" + System.currentTimeMillis() + ".txt"));
            w.write("pusher-profile-problem 1\n");
            w.write("message " + message.replace('\n', ' ') + "\n");
        } catch (IOException ignored) {
            // Nothing left to try. The log line above is the last word.
        } finally {
            close(w);
        }
    }

    private static void close(FileWriter w) {
        if (w == null) {
            return;
        }
        try {
            w.close();
        } catch (IOException ignored) {
        }
    }

    @Override
    public void onOpModePreInit(OpMode opMode) {
    }

    @Override
    public void onOpModePreStart(OpMode opMode) {
        // The stop robot OpMode is what the robot sits in between runs. It is
        // selected on every stop, and profiling it would write a recording of
        // the robot doing nothing, over and over.
        if (isDefault(opMode)) {
            return;
        }

        stopSampler();
        reset();

        opModeName = nameOf(opMode);
        opModeClass = opMode.getClass().getName();
        startedAt = System.currentTimeMillis();
        startedNanos = System.nanoTime();
        recording = true;

        running = true;
        sampler = new Thread(new Runnable() {
            @Override
            public void run() {
                sample();
            }
        }, "PusherLoopProfiler");
        sampler.setDaemon(true);
        // Just above the OpMode so a busy robot does not starve the sampler,
        // which would show up as a run that recorded far fewer samples than it
        // should have and quietly understate everything.
        sampler.setPriority(Thread.NORM_PRIORITY + 1);
        sampler.start();
    }

    @Override
    public void onOpModePostStop(OpMode opMode) {
        if (isDefault(opMode) || !recording) {
            return;
        }

        stopSampler();
        recording = false;

        try {
            write();
        } catch (Exception e) {
            RobotLog.ee(TAG, e, "could not write the profile");
            problem("The profile for " + opModeName + " could not be written: " + e);
        }
    }

    /**
     * Whether this is the SDK's own do-nothing OpMode.
     *
     * By type rather than by name: the name is a string the SDK is free to
     * change, and getting this wrong means every stop writes a recording.
     */
    private static boolean isDefault(OpMode opMode) {
        return opMode == null || opMode instanceof OpModeManagerImpl.DefaultOpMode;
    }

    private static String nameOf(OpMode opMode) {
        String name = null;
        try {
            if (opMode.getClass().getSimpleName().length() > 0) {
                name = opMode.getClass().getSimpleName();
            }
        } catch (Exception ignored) {
        }
        if (name == null || name.length() == 0) {
            name = "OpMode";
        }
        return name.replace(' ', '_');
    }

    private void reset() {
        nodes.clear();
        runs.clear();
        root = new Node(0, null, "all");
        nodes.add(root);
        samples = 0;
        missed = 0;
        truncated = 0;
        target = null;
    }

    private void stopSampler() {
        running = false;

        Thread t = sampler;
        sampler = null;
        if (t == null) {
            return;
        }

        try {
            t.join(500);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }

    /** The sampling loop, on its own thread. */
    private void sample() {
        long next = System.nanoTime();

        while (running) {
            next += PERIOD_MS * 1000000L;

            try {
                tick();
            } catch (Exception e) {
                missed++;
            }

            long wait = next - System.nanoTime();
            if (wait < 0) {
                // Behind. Give up the missed ticks rather than spinning to catch
                // up, which would sample in a burst and misreport the shape of
                // the run.
                next = System.nanoTime();
                continue;
            }

            try {
                Thread.sleep(wait / 1000000L, (int) (wait % 1000000L));
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                return;
            }
        }
    }

    private void tick() {
        if (samples >= MAX_SAMPLES) {
            return;
        }

        Thread t = target;
        if (t == null || !t.isAlive()) {
            t = findOpModeThread();
            target = t;
        }
        if (t == null) {
            missed++;
            return;
        }

        StackTraceElement[] stack = t.getStackTrace();
        if (stack == null || stack.length == 0) {
            missed++;
            return;
        }

        add(stack);
    }

    /**
     * The thread the OpMode is running on, found by looking for its own class in
     * the stacks.
     *
     * By what it is doing rather than by what it is called. The SDK runs an
     * iterative OpMode's loop() on the event loop thread and a LinearOpMode's
     * runOpMode() on one of its own, and promises the name of neither, so a
     * name would have been two guesses instead of one measurement.
     */
    private Thread findOpModeThread() {
        Map<Thread, StackTraceElement[]> all;
        try {
            all = Thread.getAllStackTraces();
        } catch (Exception e) {
            return null;
        }

        for (Map.Entry<Thread, StackTraceElement[]> entry : all.entrySet()) {
            if (entry.getKey() == Thread.currentThread()) {
                continue;
            }
            for (StackTraceElement frame : entry.getValue()) {
                if (opModeClass.equals(frame.getClassName())) {
                    return entry.getKey();
                }
            }
        }

        return null;
    }

    /** Files one stack into the tree and onto the timeline. */
    private void add(StackTraceElement[] stack) {
        int depth = stack.length;
        if (depth > MAX_DEPTH) {
            depth = MAX_DEPTH;
            truncated++;
        }

        Node at = root;

        // Walked from the bottom, because a stack trace is handed over top
        // first and a tree grows from its root.
        for (int i = depth - 1; i >= 0; i--) {
            String name = frameName(stack[i]);

            if (at.kids == null) {
                at.kids = new HashMap<>();
            }

            Node kid = at.kids.get(name);
            if (kid == null) {
                if (nodes.size() >= MAX_NODES) {
                    // Out of room for new paths. Everything from here on is
                    // counted against where it got to, which keeps the totals
                    // honest even though the detail is gone.
                    break;
                }
                kid = new Node(nodes.size(), at, name);
                nodes.add(kid);
                at.kids.put(name, kid);
            }
            at = kid;
        }

        at.self++;
        samples++;

        int[] last = runs.isEmpty() ? null : runs.get(runs.size() - 1);
        if (last != null && last[0] == at.id) {
            last[1]++;
            return;
        }
        runs.add(new int[]{at.id, 1});
    }

    private static String frameName(StackTraceElement frame) {
        String cls = frame.getClassName();
        String method = frame.getMethodName();

        if (cls == null) {
            cls = "?";
        }
        if (method == null) {
            method = "?";
        }
        return cls + "." + method;
    }

    /**
     * Writes the run.
     *
     * Nothing is written while the OpMode is running: a recording is a few tens
     * of kilobytes and the point of the exercise is to not be the thing costing
     * the loop its time.
     */
    private void write() throws IOException {
        File dir = new File(DIR);
        if (!dir.exists() && !dir.mkdirs()) {
            throw new IOException("cannot create " + DIR);
        }

        File out = new File(dir, opModeName + "-" + startedAt + ".txt");
        long durationMs = (System.nanoTime() - startedNanos) / 1000000L;

        FileWriter w = null;
        try {
            w = new FileWriter(out);

            w.write("pusher-profile 1\n");
            w.write("opmode " + opModeName + "\n");
            w.write("class " + opModeClass + "\n");
            w.write("started " + startedAt + "\n");
            w.write("period-ms " + PERIOD_MS + "\n");
            w.write("duration-ms " + durationMs + "\n");
            w.write("samples " + samples + "\n");
            w.write("missed " + missed + "\n");
            w.write("truncated " + truncated + "\n");

            for (int i = 1; i < nodes.size(); i++) {
                Node n = nodes.get(i);
                w.write(String.format(Locale.US, "node %d %d %d %s\n",
                        n.id, n.parent == null ? 0 : n.parent.id, n.self, n.name));
            }

            for (int i = 0; i < runs.size(); i++) {
                int[] run = runs.get(i);
                w.write("run " + run[0] + " " + run[1] + "\n");
            }
        } finally {
            close(w);
        }

        RobotLog.ii(TAG, "wrote " + out.getAbsolutePath() + " (" + samples + " samples)");
    }
}
`
